---
- name: Include OS specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - 'vars'
  tags:
    - install
    - config

- name: include influxdb installation
  include: "influxdb_installation_{{ ansible_os_family }}.yml"
  tags:
    - install

- name: include influxdb post-installation
  include: "influxdb_post_installation.yml"
  tags:
    - install

- name: include basic influxdb configuration
  include: "influxdb_configuration.yml"
  vars:
    _global:
      bind-address: 127.0.0.1:8088
    _http:
      bind-address: 127.0.0.1:8086
      auth-enabled: true
      ping-auth-enabled: true
      https-enabled: false
    internal_influxdb_config_global: "{{ influxdb_config_global | combine(_global, recursive=True) }}"
    internal_influxdb_config_http: "{{ influxdb_config_http | combine(_http, recursive=True) }}"
  tags:
    - config
    - install

- name: include influxdb authorization
  include: "influxdb_authorization.yml"
  when: ( influxdb_admin_username and influxdb_admin_password )
  tags:
    - config
    - install
    - manage-content

- name: include influxdb database creation
  include: "influxdb_manage_databases.yml"
  tags:
    - install
    - manage-content

- name: final influxdb configuration
  include: "influxdb_configuration.yml"
  vars:
    internal_influxdb_config_global: "{{ influxdb_config_global }}"
    internal_influxdb_config_http: "{{ influxdb_config_http }}"
  tags:
    - config
